# Generated by Django 4.1.7 on 2023-03-07 23:44

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_address_customuser_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='best_seller_image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.bestseller_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=api.models.product_directory_path),
        ),
    ]
